### ISSUE TITLE
Bulletin list margin issue

### ISSUE THREAD

**Issue by djhuistra** [Orange-Murker/quill_delta_pdf#1]
This image from the quill editor:

![image](https://github.com/Orange-Murker/quill_delta_pdf/assets/4253972/474ae94a-78a7-47a0-abc9-e9e8613eb4ed)

Results in this PDF:

![image](https://github.com/Orange-Murker/quill_delta_pdf/assets/4253972/0d16ae1b-fbc4-493d-b5ee-a39d88605ab8)

the bulletin list in the pdf should have more padding on the left, so it is more like in the quill editor in my opinion

**Comment by Orange-Murker** [comment]
Fixed in b1ac48c84c3e68e32b723419b2bbb3411642cf63

Will release a new version soon
